config/routes.rb
Rails.application.routes.draw do

  resources :playlists do 
  	resources :songs, only: [:create, :destroy]
  end

  resources :users


  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many  :songs
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :playlist
  validates :artist, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :playlists
	validates :name, presence: true
	validates :name, uniqueness: true
	validates :email, presence: true
	validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    
    @song = Song.new
    @canciones = Song.all
    
  end

  # GET /playlists/new
  def new
    @usuarios = User.all
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name, :user_id)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_action :set_playlist, only: [:create,:destroy]
	def create
		@song = Song.new(songs_params)		
		@song.playlist = @playlist

		@song.save
		
		redirect_to @playlist, notice: 'La Canción se ha creado con éxito'
	end

	def destroy
		song = Song.find(params[:id])
		song.destroy
		
		redirect_to @playlist, notice: 'La canción se ha eliminado con éxito'
	end
	
	private
		def songs_params
			params.require(:song).permit(:artist, :name)
		end
		
		def set_playlist
			@playlist = Playlist.find(params[:playlist_id])
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Musify</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>"">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= users_path %>">Users</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= playlists_path %>">PlayList</a>
      </li>
      
    </ul>
  </div>
</nav>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_with(model: playlist, local: true) do |form| %>
  <% if playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :playlist_name %>
  </div>
  
  <div class="field">
  <%= form.label :user_id %>
  <%= form.select :user_id, User.all.collect{|x| [x.name, x.id]}, id: :playlist_user_id, prompt: "Seleccione un usuario" %>
</div>

  

  <div class="actions">
    <%= form.submit 'Crear List', class: "btn btn-success"  %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<div class="container card bg-light">
	<h1>Editando Playlist</h1>

<%= render 'form', playlist: @playlist %> <br>
<div>
<%= link_to 'Mostrar', @playlist, class: "btn btn-warning" %> <br>
</div><br>
<div>
	<%= link_to 'Atras', playlists_path, class: "btn btn-info" %>
</div>


</div>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Playlists</h1>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Usuario</th>
      <th>Canciones</th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= playlist.user.name %></td>
         <td><%= playlist.songs.count %></td>

        <td><%= link_to 'Show', playlist, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_playlist_path, class: "btn btn-primary"%>
</div>

app/views/playlists/new.html.erb
<div class="container card bg-light">



<h1>Nueva Playlist</h1>

<%= render 'form', playlist: @playlist %>
<div>
<%= link_to 'Back', playlists_path, class: "btn btn-light" %>
</div>
</div>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<p>
  <strong>Name:</strong>
  <%= @playlist.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @playlist.user.name %>
</p>

<%= link_to 'Edit', edit_playlist_path(@playlist),class: "btn btn-light" %> |
<%= link_to 'Back', playlists_path, class: "btn btn-light" %>


<hr>
<%= form_with(model: [@playlist, @song], local: true) do |f| %>
 
 <%= f.label :artist %>
 <%= f.text_field :artist %>

<%= f.label :name %> 
<%= f.text_field :name %>

 <%= f.submit :guardar %>
<% end %>
<table class = "table table-striped">
	<thead>
    <tr>
      <th>Artista</th>
      
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
<% @canciones.each do |cancion|%>
<tr>
	<td><%= cancion.artist %></td>
	
<td><%= cancion.name %></td>
	

<td><%= link_to 'Borrar', playlist_song_path(@playlist, cancion), method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
<% end %>

</tr>
</table>

app/views/users/_form.html.erb
<br>
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>
<br>
<br>
  <div class="actions">
    <%= form.submit 'Guardar' , class: "btn btn-success" %>
  </div>
  <br>
<% end %>

app/views/users/edit.html.erb
<br>
<div class="container card bg-light">
	<h1>Editar Usuario</h1>

<%= render 'form', user: @user %>
<div>
	<%= link_to 'Mostrar', @user, class: "btn btn-warning" %>
	<%= link_to 'Atras', users_path, class: "btn btn-info" %>
</div>

  <div>
 	
 </div>


</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Users</h1>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th> Playlist </th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.playlists.count %></td>
        
        <td><%= link_to 'Show', user, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger"%> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path , class: "btn btn-primary" %>

</div>

app/views/users/new.html.erb
<br>



<div class="container card bg-light">
	<br>
	<h1>Nuevo Usuario</h1>

<%= render 'form', user: @user %> <br>
<br>
<div>
	<%= link_to 'atras', users_path, class: "btn btn-info" %> <br> <br>
</div>


</Div>

app/views/users/show.html.erb
<br>
<div class="container card bg-light">

<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<div>
	<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-warning" %> 

</div>
<br>
<div>
	<%= link_to 'Back', users_path, class: "btn btn-light" %>
</div>

</div>